### PR TITLE
Multi pv test fix

### LINKED ISSUE #113: Passing test includes an output error.
**Actual behavior**
The rspec test `can process multiple PV's` passes, but the stderr output to terminal includes an error with the text: `Cannot write - <path/to/scenario_report_multiPV_reopt_run.json>`. That doesn't seem right.

**To Reproduce**

1. `rspec`

### PR DESCRIPTION
**Pull request by vtnate**
### Pull Request Description

- The multi-PV test was expecting a directory that hadn't been created. The missing dir (among others) and its contents get deleted a few lines below, so I fixed the path to not include that dir.
- Added a check for the file that was missing, which should have been there all along and cause the test to fail.

### Checklist (Delete lines that don't apply)

- [x] Unit tests have been added or updated
- [x] All ci tests pass (green)
- [x] An [issue](https://github.com/urbanopt/urbanopt-reopt-gem/issues) has been created (which will be used for the changelog)
- [x] This branch is up-to-date with develop

### CODE REVIEW

File: spec/tests/urbanopt_reopt_spec.rb [hunk 1]
```diff
@@ -173,7 +174,7 @@
     end
     scenario_report = URBANopt::Reporting::DefaultReports::ScenarioReport.new
 
-    scenario_report_dir = File.join(File.dirname(__FILE__), '../run/example_scenario')
+    scenario_report_dir = Pathname(__FILE__).dirname.parent / 'run' / 'example_scenario'
```
Comment (vtnate) [inline spec/tests/urbanopt_reopt_spec.rb:177]: The Ruby analog of Pathlib! 💘

**Review by kflemin — APPROVED** [review]
🏆
